### PR TITLE
Typo in package.json

### PR DESCRIPTION
**Pull request by Ibuprofen**

### CODE REVIEW

**Comment by hedgerh** [comment]
@Ibuprofen Thanks!  This is kind of an experimental boilerplate from when I was trying to figure out how to set up webpack.  I think it could use some work.  Any feedback you could give me would be greatly appreciated in regards to your needs and what you're trying to do.  Also, if you find some reliable way to live reload a react/webpack based chrome extension, let me know!

**Comment by Ibuprofen** [comment]
Thanks for tossing this up on the web! It has already saved me time. This is pretty new territory for myself as well but I'll be sure to open any PR I think are helpful.

Live reload would be very nice! I'll let you know if I find anything.

**Comment by hedgerh** [comment]
@Ibuprofen For sure.  Oh man. I just started looking into live reloading and came across this https://chrome.google.com/webstore/detail/extensions-reloader/fimgfedafeadlieiabdeeaodndnlbhid
And on github: https://github.com/arikw/chrome-extensions-reloader

It could possibly be worked into the webpack build process. I'll have to look into it.

**Comment by Ibuprofen** [comment]
Oooo yeah looks like there is a pretty straightforward on/off. I'm not sure though how webpack and chrome will talk?

I know chrome can send messages from background pages to the content scripts, but I'm not sure how we'd go about messaging from outside of chrome. This is maybe the overly complex way but I wonder if the extension can run a small express server (only in dev mode of course), which when poked, executes the reload?  Ehhh

**Pull request merged**
